apiVersion: clustermigration.com/v1
kind: multiclustercanary
metadata:
  name: canary-for-frontend-svc
spec:
  gtpName: gtp1
  gtpNamespace: default
  gtpOldDestination: 'app1.default.east.cluster1'
  gtpNewDestination: 'app1.default.west.cluster2'
  healthThreshold: 90
