apiVersion: citrix.com/v1beta1
kind: canary
metadata:
  name: canary-for-app1-svc
spec:
  gtpName: gtp1
  gtpNamespace: default
  sourceCluster: 'app1.default.east.cluster1'
  destinationCluster: 'app1.default.west.cluster2'
  healthMonitoringLbName: "lb1"
  healthMonitoringInterval: 1
  healthScoreThreshold: 90
