apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: canaries.citrix.com
spec:
  scope: Namespaced
  group: citrix.com
  version: v1beta1
  names:
    kind: canary
    singular: canary
    plural: canaries
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            gtpName:
              type: string
              description: "Name of the Global Traffic Policy on which canary will be applied"
            gtpNamespace:
              type: string
              description: "Namespace of the Global Traffic Policy on which canary will be applied"
            sourceCluster:
              type: string
              description: "Old destination cluster in app.namespace.region.cluster format, from which app traffic will be migrated"
            destinationCluster:
              type: string
              description: "New destination cluster in app.namespace.region.cluster format, to which app traffic will be migrated"
            healthMonitoringLbName:
              type: string
              description: "Name of the LB vserver that has to be monitored on the new cluster for qualifying the quality of the new deployment"
            healthMonitoringInterval:
              type: integer
              description: "Monitoring interval in seconds"
            healthScoreThreshold:
              type: integer
              description: "Health threshold in percentage. If health score goes below this value during migration, a rollback will be triggered"
              minimum: 1
              maximum: 100
